const FETCH_CATEGORIES = "FETCH_CATEGORIES";
const POST_CATEGORIES = "POST_CATEGORIES";
const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
const ADD_CATEGORY = "ADD_CATEGORY";

export { ADD_CATEGORY, FETCH_CATEGORIES, UPDATE_CATEGORIES, POST_CATEGORIES };
